from __future__ import annotations

ORACLE_MAX_VARCHAR2_CHAR = 4000
ORACLE_MAX_IDENTIFIER_LEN_LEGACY = 30
ORACLE_MAX_IDENTIFIER_LEN_EXTENDED = 128
varchar2_growth_buffer = 50
ORACLE_DATATYPES = ["VARCHAR2", "NUMBER", "DATE", "TIMESTAMP", "UNKNOWN"]

_ORACLE_RESERVED = frozenset({
"ACCESS","ADD","ALL","ALTER","AND","ANY","AS","ASC","AUDIT","BETWEEN","BY","CHAR","CHECK","CLUSTER","COLUMN",
"COMMENT","COMPRESS","CONNECT","CREATE","CURRENT","DATE","DECIMAL","DEFAULT","DELETE","DESC","DISTINCT","DROP","ELSE",
"EXCLUSIVE","EXISTS","FILE","FLOAT","FOR","FROM","GRANT","GROUP","HAVING","IDENTIFIED","IMMEDIATE","IN","INCREMENT",
"INDEX","INITIAL","INSERT","INTEGER","INTERSECT","INTO","IS","LEVEL","LIKE","LOCK","LONG","MAXEXTENTS","MINUS",
"MLSLABEL","MODE","MODIFY","NOAUDIT","NOCOMPRESS","NOT","NOWAIT","NULL","NUMBER","OF","OFFLINE","ON","ONLINE",
"OPTION","OR","ORDER","PCTFREE","PRIOR","PRIVILEGES","PUBLIC","RAW","RENAME","RESOURCE","REVOKE","ROW","ROWID",
"ROWNUM","ROWS","SELECT","SESSION","SET","SHARE","SIZE","SMALLINT","START","SUCCESSFUL","SYNONYM","SYSDATE",
"TABLE","THEN","TO","TRIGGER","UID","UNION","UNIQUE","UPDATE","USER","VALIDATE","VALUES","VARCHAR","VARCHAR2",
"VIEW","WHENEVER","WHERE","WITH"})

def effective_max_varchar2(observed_char_len: int) -> int:
    if observed_char_len > ORACLE_MAX_VARCHAR2_CHAR:
        raise ValueError(f"observed_char_len {observed_char_len} exceeds Oracle limit {ORACLE_MAX_VARCHAR2_CHAR}")
    buffered = observed_char_len + varchar2_growth_buffer
    return min(buffered, ORACLE_MAX_VARCHAR2_CHAR)
