// This file is auto-generated by @hey-api/openapi-ts

export const Body_create_data_api_data_insert_putSchema = {
    properties: {
        catalog_json: {
            type: 'string',
            title: 'Catalog Json',
            description: 'The Catalog AST as a JSON string'
        },
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File',
            description: 'The Arrow IPC Stream binary'
        }
    },
    type: 'object',
    required: [
        'catalog_json',
        'file'
    ],
    title: 'Body_create_data_api_data_insert_put'
} as const;

export const Body_delete_data_api_data__deleteSchema = {
    properties: {
        catalog_json: {
            type: 'string',
            title: 'Catalog Json',
            description: 'The Catalog AST as a JSON string'
        },
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File',
            description: 'The Arrow IPC Stream binary'
        }
    },
    type: 'object',
    required: [
        'catalog_json',
        'file'
    ],
    title: 'Body_delete_data_api_data__delete'
} as const;

export const Body_loginSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login'
} as const;

export const Body_update_data_api_data__patchSchema = {
    properties: {
        catalog_json: {
            type: 'string',
            title: 'Catalog Json',
            description: 'The Catalog AST as a JSON string'
        },
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File',
            description: 'The Arrow IPC Stream binary'
        }
    },
    type: 'object',
    required: [
        'catalog_json',
        'file'
    ],
    title: 'Body_update_data_api_data__patch'
} as const;

export const Body_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        },
        registry_key: {
            type: 'string',
            title: 'Registry Key'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_upload_file'
} as const;

export const Body_upsert_data_api_data__putSchema = {
    properties: {
        catalog_json: {
            type: 'string',
            title: 'Catalog Json',
            description: 'The Catalog AST as a JSON string'
        },
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File',
            description: 'The Arrow IPC Stream binary'
        }
    },
    type: 'object',
    required: [
        'catalog_json',
        'file'
    ],
    title: 'Body_upsert_data_api_data__put'
} as const;

export const Catalog_InputSchema = {
    properties: {
        catalog_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Catalog Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        namespace: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Namespace'
        },
        version: {
            type: 'integer',
            title: 'Version',
            default: 1
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        scope: {
            type: 'string',
            enum: [
                'SYSTEM',
                'TEAM',
                'USER'
            ],
            title: 'Scope',
            default: 'USER'
        },
        source_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'salesforce',
                        'oracle',
                        'reader',
                        'excel'
                    ]
                },
                {
                    type: 'string',
                    const: 'federation'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Type'
        },
        entities: {
            items: {
                $ref: '#/components/schemas/Entity'
            },
            type: 'array',
            title: 'Entities'
        },
        operator_groups: {
            items: {
                $ref: '#/components/schemas/OperatorGroup-Input'
            },
            type: 'array',
            title: 'Operator Groups'
        },
        joins: {
            items: {
                $ref: '#/components/schemas/Join'
            },
            type: 'array',
            title: 'Joins'
        },
        sort_columns: {
            items: {
                $ref: '#/components/schemas/Sort'
            },
            type: 'array',
            title: 'Sort Columns'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        offset: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offset'
        },
        owner_username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Username'
        },
        team_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Team Id'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    title: 'Catalog'
} as const;

export const Catalog_OutputSchema = {
    properties: {
        catalog_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Catalog Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        namespace: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Namespace'
        },
        version: {
            type: 'integer',
            title: 'Version',
            default: 1
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        scope: {
            type: 'string',
            enum: [
                'SYSTEM',
                'TEAM',
                'USER'
            ],
            title: 'Scope',
            default: 'USER'
        },
        source_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'salesforce',
                        'oracle',
                        'reader',
                        'excel'
                    ]
                },
                {
                    type: 'string',
                    const: 'federation'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Type'
        },
        entities: {
            items: {
                $ref: '#/components/schemas/Entity'
            },
            type: 'array',
            title: 'Entities'
        },
        operator_groups: {
            items: {
                $ref: '#/components/schemas/OperatorGroup-Output'
            },
            type: 'array',
            title: 'Operator Groups'
        },
        joins: {
            items: {
                $ref: '#/components/schemas/Join'
            },
            type: 'array',
            title: 'Joins'
        },
        sort_columns: {
            items: {
                $ref: '#/components/schemas/Sort'
            },
            type: 'array',
            title: 'Sort Columns'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        offset: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offset'
        },
        owner_username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Username'
        },
        team_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Team Id'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    title: 'Catalog'
} as const;

export const ColumnSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        locator: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Locator'
                },
                {
                    type: 'null'
                }
            ]
        },
        raw_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Type'
        },
        arrow_type_id: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'null',
                        'bool',
                        'int8',
                        'int16',
                        'int32',
                        'int64',
                        'uint8',
                        'uint16',
                        'uint32',
                        'uint64',
                        'float16',
                        'float32',
                        'float64',
                        'string',
                        'utf8',
                        'large_string',
                        'binary',
                        'large_binary',
                        'date32',
                        'date64',
                        'timestamp_s',
                        'timestamp_ms',
                        'timestamp_us',
                        'timestamp_ns',
                        'time32_s',
                        'time32_ms',
                        'time64_us',
                        'time64_ns',
                        'duration_s',
                        'duration_ms',
                        'duration_us',
                        'duration_ns',
                        'decimal128',
                        'decimal256',
                        'json',
                        'uuid',
                        'string_view',
                        'list',
                        'large_list',
                        'struct',
                        'map',
                        'list_view',
                        'large_list_view',
                        'dictionary'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Arrow Type Id'
        },
        arrow_type_meta: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Arrow Type Meta'
        },
        primary_key: {
            type: 'boolean',
            title: 'Primary Key',
            default: false
        },
        is_unique: {
            type: 'boolean',
            title: 'Is Unique',
            default: false
        },
        is_nullable: {
            type: 'boolean',
            title: 'Is Nullable',
            default: true
        },
        is_read_only: {
            type: 'boolean',
            title: 'Is Read Only',
            default: false
        },
        is_compound_key: {
            type: 'boolean',
            title: 'Is Compound Key',
            default: false
        },
        is_foreign_key: {
            type: 'boolean',
            title: 'Is Foreign Key',
            default: false
        },
        foreign_key_entity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Foreign Key Entity'
        },
        foreign_key_column: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Foreign Key Column'
        },
        is_foreign_key_enforced: {
            type: 'boolean',
            title: 'Is Foreign Key Enforced',
            default: false
        },
        max_length: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Length'
        },
        precision: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precision'
        },
        scale: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scale'
        },
        serialized_null_value: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serialized Null Value'
        },
        default_value: {
            title: 'Default Value'
        },
        enum_values: {
            items: {},
            type: 'array',
            title: 'Enum Values'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        },
        ordinal_position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ordinal Position'
        },
        is_computed: {
            type: 'boolean',
            title: 'Is Computed',
            default: false
        },
        is_deprecated: {
            type: 'boolean',
            title: 'Is Deprecated',
            default: false
        },
        is_hidden: {
            type: 'boolean',
            title: 'Is Hidden',
            default: false
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'Column'
} as const;

export const EntitySchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        namespace: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Namespace'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        entity_type: {
            type: 'string',
            enum: [
                'table',
                'view',
                'materialized_view',
                'external',
                'api_endpoint',
                'procedure',
                'file',
                'unknown'
            ],
            title: 'Entity Type',
            default: 'unknown'
        },
        plugin: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'salesforce',
                        'oracle',
                        'reader',
                        'excel'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plugin'
        },
        row_count_estimate: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Row Count Estimate'
        },
        columns: {
            items: {
                $ref: '#/components/schemas/Column'
            },
            type: 'array',
            title: 'Columns'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'Entity'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const JoinSchema = {
    properties: {
        left_entity: {
            $ref: '#/components/schemas/Entity'
        },
        left_column: {
            $ref: '#/components/schemas/Column'
        },
        right_entity: {
            $ref: '#/components/schemas/Entity'
        },
        right_column: {
            $ref: '#/components/schemas/Column'
        },
        join_type: {
            type: 'string',
            enum: [
                'INNER',
                'LEFT',
                'OUTER'
            ],
            title: 'Join Type',
            default: 'INNER'
        }
    },
    type: 'object',
    required: [
        'left_entity',
        'left_column',
        'right_entity',
        'right_column'
    ],
    title: 'Join'
} as const;

export const LocatorSchema = {
    properties: {
        plugin: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'salesforce',
                        'oracle',
                        'reader',
                        'excel'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plugin'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        is_file: {
            type: 'boolean',
            title: 'Is File',
            default: false
        },
        environment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Environment'
        },
        namespace: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Namespace'
        },
        entity_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Name'
        },
        additional_locators: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Additional Locators'
        }
    },
    type: 'object',
    title: 'Locator',
    description: 'The strict contract defining the absolute origin of a scalar'
} as const;

export const MigrationEntityResultSchema = {
    properties: {
        entity: {
            type: 'string',
            title: 'Entity'
        },
        target: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'entity',
        'status'
    ],
    title: 'MigrationEntityResult'
} as const;

export const MigrationRequestSchema = {
    properties: {
        source_plugin: {
            type: 'string',
            title: 'Source Plugin'
        },
        target_plugin: {
            type: 'string',
            title: 'Target Plugin'
        },
        entities: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entities'
        },
        source_catalog_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Catalog Name'
        },
        target_catalog_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Catalog Name'
        }
    },
    type: 'object',
    required: [
        'source_plugin',
        'target_plugin'
    ],
    title: 'MigrationRequest'
} as const;

export const MigrationResultSchema = {
    properties: {
        results: {
            items: {
                $ref: '#/components/schemas/MigrationEntityResult'
            },
            type: 'array',
            title: 'Results'
        },
        succeeded: {
            type: 'integer',
            title: 'Succeeded'
        },
        failed: {
            type: 'integer',
            title: 'Failed'
        }
    },
    type: 'object',
    required: [
        'results',
        'succeeded',
        'failed'
    ],
    title: 'MigrationResult'
} as const;

export const OperationSchema = {
    properties: {
        independent: {
            $ref: '#/components/schemas/Column'
        },
        operator: {
            type: 'string',
            enum: [
                '=',
                '==',
                '!=',
                '>',
                '<',
                '>=',
                '<=',
                'IN',
                'NOT IN',
                'LIKE',
                'NOT LIKE',
                'BETWEEN',
                'NOT BETWEEN',
                'IS NULL',
                'IS NOT NULL'
            ],
            title: 'Operator'
        },
        dependent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    items: {},
                    type: 'array'
                },
                {
                    $ref: '#/components/schemas/Column'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dependent'
        }
    },
    type: 'object',
    required: [
        'independent',
        'operator',
        'dependent'
    ],
    title: 'Operation',
    description: 'The single equal sign \'=\' is an assignment operator, it is not an equality operator.'
} as const;

export const OperatorGroup_InputSchema = {
    properties: {
        condition: {
            type: 'string',
            enum: [
                'AND',
                'OR',
                'NOT'
            ],
            title: 'Condition'
        },
        operation_group: {
            items: {
                anyOf: [
                    {
                        $ref: '#/components/schemas/Operation'
                    },
                    {
                        $ref: '#/components/schemas/OperatorGroup-Input'
                    }
                ]
            },
            type: 'array',
            title: 'Operation Group'
        }
    },
    type: 'object',
    required: [
        'condition'
    ],
    title: 'OperatorGroup'
} as const;

export const OperatorGroup_OutputSchema = {
    properties: {
        condition: {
            type: 'string',
            enum: [
                'AND',
                'OR',
                'NOT'
            ],
            title: 'Condition'
        },
        operation_group: {
            items: {
                anyOf: [
                    {
                        $ref: '#/components/schemas/Operation'
                    },
                    {
                        $ref: '#/components/schemas/OperatorGroup-Output'
                    }
                ]
            },
            type: 'array',
            title: 'Operation Group'
        }
    },
    type: 'object',
    required: [
        'condition'
    ],
    title: 'OperatorGroup'
} as const;

export const SortSchema = {
    properties: {
        column: {
            $ref: '#/components/schemas/Column'
        },
        direction: {
            type: 'string',
            enum: [
                'ASC',
                'DESC'
            ],
            title: 'Direction',
            default: 'ASC'
        },
        nulls_first: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nulls First'
        }
    },
    type: 'object',
    required: [
        'column'
    ],
    title: 'Sort'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: [
        'access_token',
        'token_type'
    ],
    title: 'Token'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'username',
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserOutSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        }
    },
    type: 'object',
    required: [
        'username',
        'email'
    ],
    title: 'UserOut',
    description: 'Safe API response shape - no credentials.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
