// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateLeadData, CreateLeadErrors, CreateLeadResponses, GetLeadsData, GetLeadsResponses, GetUserData, GetUserResponses, LoginData, LoginErrors, LoginResponses, PostUserData, PostUserErrors, PostUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Register User
 */
export const postUser = <ThrowOnError extends boolean = false>(options: Options<PostUserData, ThrowOnError>) => (options.client ?? client).post<PostUserResponses, PostUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/users/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get User
 */
export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) => (options?.client ?? client).get<GetUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/',
    ...options
});

/**
 * Read Leads
 */
export const getLeads = <ThrowOnError extends boolean = false>(options?: Options<GetLeadsData, ThrowOnError>) => (options?.client ?? client).get<GetLeadsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/leads/',
    ...options
});

/**
 * Create Lead
 */
export const createLead = <ThrowOnError extends boolean = false>(options: Options<CreateLeadData, ThrowOnError>) => (options.client ?? client).post<CreateLeadResponses, CreateLeadErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/leads/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
