// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Lead
 */
export type Lead = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Owner Id
     */
    owner_id?: number | null;
};

/**
 * LeadCreate
 */
export type LeadCreate = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Status
     */
    status?: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserBase
 */
export type UserBase = {
    /**
     * Username
     */
    username: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type PostUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users/register';
};

export type PostUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUserError = PostUserErrors[keyof PostUserErrors];

export type PostUserResponses = {
    /**
     * Successful Response
     */
    200: UserBase;
};

export type PostUserResponse = PostUserResponses[keyof PostUserResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UserBase;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetLeadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leads/';
};

export type GetLeadsResponses = {
    /**
     * Response Get Leads
     *
     * Successful Response
     */
    200: Array<Lead>;
};

export type GetLeadsResponse = GetLeadsResponses[keyof GetLeadsResponses];

export type CreateLeadData = {
    body: LeadCreate;
    path?: never;
    query?: never;
    url: '/api/leads/';
};

export type CreateLeadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLeadError = CreateLeadErrors[keyof CreateLeadErrors];

export type CreateLeadResponses = {
    /**
     * Successful Response
     */
    200: Lead;
};

export type CreateLeadResponse = CreateLeadResponses[keyof CreateLeadResponses];
