// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Body_create_data_api_data_insert_put
 */
export type BodyCreateDataApiDataInsertPut = {
    /**
     * Catalog Json
     *
     * The Catalog AST as a JSON string
     */
    catalog_json: string;
    /**
     * File
     *
     * The Arrow IPC Stream binary
     */
    file: Blob | File;
};

/**
 * Body_delete_data_api_data__delete
 */
export type BodyDeleteDataApiDataDelete = {
    /**
     * Catalog Json
     *
     * The Catalog AST as a JSON string
     */
    catalog_json: string;
    /**
     * File
     *
     * The Arrow IPC Stream binary
     */
    file: Blob | File;
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_update_data_api_data__patch
 */
export type BodyUpdateDataApiDataPatch = {
    /**
     * Catalog Json
     *
     * The Catalog AST as a JSON string
     */
    catalog_json: string;
    /**
     * File
     *
     * The Arrow IPC Stream binary
     */
    file: Blob | File;
};

/**
 * Body_upload_file
 */
export type BodyUploadFile = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Registry Key
     */
    registry_key?: string;
};

/**
 * Body_upsert_data_api_data__put
 */
export type BodyUpsertDataApiDataPut = {
    /**
     * Catalog Json
     *
     * The Catalog AST as a JSON string
     */
    catalog_json: string;
    /**
     * File
     *
     * The Arrow IPC Stream binary
     */
    file: Blob | File;
};

/**
 * Catalog
 */
export type CatalogInput = {
    /**
     * Catalog Id
     */
    catalog_id?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Alias
     */
    alias?: string | null;
    /**
     * Namespace
     */
    namespace?: string | null;
    /**
     * Version
     */
    version?: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scope
     */
    scope?: 'SYSTEM' | 'TEAM' | 'USER';
    /**
     * Source Type
     */
    source_type?: 'salesforce' | 'oracle' | 'reader' | 'excel' | 'federation' | null;
    /**
     * Entities
     */
    entities?: Array<Entity>;
    /**
     * Operator Groups
     */
    operator_groups?: Array<OperatorGroupInput>;
    /**
     * Joins
     */
    joins?: Array<Join>;
    /**
     * Sort Columns
     */
    sort_columns?: Array<Sort>;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Owner Username
     */
    owner_username?: string | null;
    /**
     * Team Id
     */
    team_id?: string | null;
    /**
     * Properties
     */
    properties?: {
        [key: string]: unknown;
    };
};

/**
 * Catalog
 */
export type CatalogOutput = {
    /**
     * Catalog Id
     */
    catalog_id?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Alias
     */
    alias?: string | null;
    /**
     * Namespace
     */
    namespace?: string | null;
    /**
     * Version
     */
    version?: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scope
     */
    scope?: 'SYSTEM' | 'TEAM' | 'USER';
    /**
     * Source Type
     */
    source_type?: 'salesforce' | 'oracle' | 'reader' | 'excel' | 'federation' | null;
    /**
     * Entities
     */
    entities?: Array<Entity>;
    /**
     * Operator Groups
     */
    operator_groups?: Array<OperatorGroupOutput>;
    /**
     * Joins
     */
    joins?: Array<Join>;
    /**
     * Sort Columns
     */
    sort_columns?: Array<Sort>;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Owner Username
     */
    owner_username?: string | null;
    /**
     * Team Id
     */
    team_id?: string | null;
    /**
     * Properties
     */
    properties?: {
        [key: string]: unknown;
    };
};

/**
 * Column
 */
export type Column = {
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias?: string | null;
    locator?: Locator | null;
    /**
     * Raw Type
     */
    raw_type?: string | null;
    /**
     * Arrow Type Id
     */
    arrow_type_id?: 'null' | 'bool' | 'int8' | 'int16' | 'int32' | 'int64' | 'uint8' | 'uint16' | 'uint32' | 'uint64' | 'float16' | 'float32' | 'float64' | 'string' | 'utf8' | 'large_string' | 'binary' | 'large_binary' | 'date32' | 'date64' | 'timestamp_s' | 'timestamp_ms' | 'timestamp_us' | 'timestamp_ns' | 'time32_s' | 'time32_ms' | 'time64_us' | 'time64_ns' | 'duration_s' | 'duration_ms' | 'duration_us' | 'duration_ns' | 'decimal128' | 'decimal256' | 'json' | 'uuid' | 'string_view' | 'list' | 'large_list' | 'struct' | 'map' | 'list_view' | 'large_list_view' | 'dictionary' | null;
    /**
     * Arrow Type Meta
     */
    arrow_type_meta?: {
        [key: string]: unknown;
    } | null;
    /**
     * Primary Key
     */
    primary_key?: boolean;
    /**
     * Is Unique
     */
    is_unique?: boolean;
    /**
     * Is Nullable
     */
    is_nullable?: boolean;
    /**
     * Is Read Only
     */
    is_read_only?: boolean;
    /**
     * Is Compound Key
     */
    is_compound_key?: boolean;
    /**
     * Is Foreign Key
     */
    is_foreign_key?: boolean;
    /**
     * Foreign Key Entity
     */
    foreign_key_entity?: string | null;
    /**
     * Foreign Key Column
     */
    foreign_key_column?: string | null;
    /**
     * Is Foreign Key Enforced
     */
    is_foreign_key_enforced?: boolean;
    /**
     * Max Length
     */
    max_length?: number | null;
    /**
     * Precision
     */
    precision?: number | null;
    /**
     * Scale
     */
    scale?: number | null;
    /**
     * Serialized Null Value
     */
    serialized_null_value?: string | null;
    /**
     * Default Value
     */
    default_value?: unknown;
    /**
     * Enum Values
     */
    enum_values?: Array<unknown>;
    /**
     * Timezone
     */
    timezone?: string | null;
    /**
     * Properties
     */
    properties?: {
        [key: string]: unknown;
    };
    /**
     * Ordinal Position
     */
    ordinal_position?: number | null;
    /**
     * Is Computed
     */
    is_computed?: boolean;
    /**
     * Is Deprecated
     */
    is_deprecated?: boolean;
    /**
     * Is Hidden
     */
    is_hidden?: boolean;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * Entity
 */
export type Entity = {
    /**
     * Name
     */
    name: string;
    /**
     * Alias
     */
    alias?: string | null;
    /**
     * Namespace
     */
    namespace?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Entity Type
     */
    entity_type?: 'table' | 'view' | 'materialized_view' | 'external' | 'api_endpoint' | 'procedure' | 'file' | 'unknown';
    /**
     * Plugin
     */
    plugin?: 'salesforce' | 'oracle' | 'reader' | 'excel' | null;
    /**
     * Row Count Estimate
     */
    row_count_estimate?: number | null;
    /**
     * Columns
     */
    columns?: Array<Column>;
    /**
     * Properties
     */
    properties?: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Join
 */
export type Join = {
    left_entity: Entity;
    left_column: Column;
    right_entity: Entity;
    right_column: Column;
    /**
     * Join Type
     */
    join_type?: 'INNER' | 'LEFT' | 'OUTER';
};

/**
 * Locator
 *
 * The strict contract defining the absolute origin of a scalar
 */
export type Locator = {
    /**
     * Plugin
     */
    plugin?: 'salesforce' | 'oracle' | 'reader' | 'excel' | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Is File
     */
    is_file?: boolean;
    /**
     * Environment
     */
    environment?: string | null;
    /**
     * Namespace
     */
    namespace?: string | null;
    /**
     * Entity Name
     */
    entity_name?: string | null;
    /**
     * Additional Locators
     */
    additional_locators?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MigrationEntityResult
 */
export type MigrationEntityResult = {
    /**
     * Entity
     */
    entity: string;
    /**
     * Target
     */
    target?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * MigrationRequest
 */
export type MigrationRequest = {
    /**
     * Source Plugin
     */
    source_plugin: string;
    /**
     * Target Plugin
     */
    target_plugin: string;
    /**
     * Entities
     */
    entities?: Array<string> | null;
    /**
     * Source Catalog Name
     */
    source_catalog_name?: string | null;
    /**
     * Target Catalog Name
     */
    target_catalog_name?: string | null;
};

/**
 * MigrationResult
 */
export type MigrationResult = {
    /**
     * Results
     */
    results: Array<MigrationEntityResult>;
    /**
     * Succeeded
     */
    succeeded: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * Operation
 *
 * The single equal sign '=' is an assignment operator, it is not an equality operator.
 */
export type Operation = {
    independent: Column;
    /**
     * Operator
     */
    operator: '=' | '==' | '!=' | '>' | '<' | '>=' | '<=' | 'IN' | 'NOT IN' | 'LIKE' | 'NOT LIKE' | 'BETWEEN' | 'NOT BETWEEN' | 'IS NULL' | 'IS NOT NULL';
    /**
     * Dependent
     */
    dependent: string | Array<unknown> | Column | null;
};

/**
 * OperatorGroup
 */
export type OperatorGroupInput = {
    /**
     * Condition
     */
    condition: 'AND' | 'OR' | 'NOT';
    /**
     * Operation Group
     */
    operation_group?: Array<Operation | OperatorGroupInput>;
};

/**
 * OperatorGroup
 */
export type OperatorGroupOutput = {
    /**
     * Condition
     */
    condition: 'AND' | 'OR' | 'NOT';
    /**
     * Operation Group
     */
    operation_group?: Array<Operation | OperatorGroupOutput>;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * Sort
 */
export type Sort = {
    column: Column;
    /**
     * Direction
     */
    direction?: 'ASC' | 'DESC';
    /**
     * Nulls First
     */
    nulls_first?: boolean | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserOut
 *
 * Safe API response shape - no credentials.
 */
export type UserOut = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * External Id
     */
    external_id?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshTokenData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DeleteCatalogApiCatalogDeleteData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/catalog/';
};

export type DeleteCatalogApiCatalogDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCatalogApiCatalogDeleteError = DeleteCatalogApiCatalogDeleteErrors[keyof DeleteCatalogApiCatalogDeleteErrors];

export type DeleteCatalogApiCatalogDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCatalogApiCatalogPatchData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/catalog/';
};

export type UpdateCatalogApiCatalogPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCatalogApiCatalogPatchError = UpdateCatalogApiCatalogPatchErrors[keyof UpdateCatalogApiCatalogPatchErrors];

export type UpdateCatalogApiCatalogPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCatalogApiCatalogPostData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/catalog/';
};

export type GetCatalogApiCatalogPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCatalogApiCatalogPostError = GetCatalogApiCatalogPostErrors[keyof GetCatalogApiCatalogPostErrors];

export type GetCatalogApiCatalogPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpsertCatalogApiCatalogPutData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/catalog/';
};

export type UpsertCatalogApiCatalogPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertCatalogApiCatalogPutError = UpsertCatalogApiCatalogPutErrors[keyof UpsertCatalogApiCatalogPutErrors];

export type UpsertCatalogApiCatalogPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCatalogApiCatalogInsertPutData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/catalog/insert';
};

export type CreateCatalogApiCatalogInsertPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCatalogApiCatalogInsertPutError = CreateCatalogApiCatalogInsertPutErrors[keyof CreateCatalogApiCatalogInsertPutErrors];

export type CreateCatalogApiCatalogInsertPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteEntityApiEntityDeleteData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/entity/';
};

export type DeleteEntityApiEntityDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEntityApiEntityDeleteError = DeleteEntityApiEntityDeleteErrors[keyof DeleteEntityApiEntityDeleteErrors];

export type DeleteEntityApiEntityDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateEntityApiEntityPatchData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/entity/';
};

export type UpdateEntityApiEntityPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEntityApiEntityPatchError = UpdateEntityApiEntityPatchErrors[keyof UpdateEntityApiEntityPatchErrors];

export type UpdateEntityApiEntityPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetEntityApiEntityPostData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/entity/';
};

export type GetEntityApiEntityPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityApiEntityPostError = GetEntityApiEntityPostErrors[keyof GetEntityApiEntityPostErrors];

export type GetEntityApiEntityPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpsertEntityApiEntityPutData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/entity/';
};

export type UpsertEntityApiEntityPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertEntityApiEntityPutError = UpsertEntityApiEntityPutErrors[keyof UpsertEntityApiEntityPutErrors];

export type UpsertEntityApiEntityPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateEntityApiEntityInsertPutData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/entity/insert';
};

export type CreateEntityApiEntityInsertPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEntityApiEntityInsertPutError = CreateEntityApiEntityInsertPutErrors[keyof CreateEntityApiEntityInsertPutErrors];

export type CreateEntityApiEntityInsertPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteColumnApiColumnDeleteData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/column/';
};

export type DeleteColumnApiColumnDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteColumnApiColumnDeleteError = DeleteColumnApiColumnDeleteErrors[keyof DeleteColumnApiColumnDeleteErrors];

export type DeleteColumnApiColumnDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateColumnApiColumnPatchData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/column/';
};

export type UpdateColumnApiColumnPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateColumnApiColumnPatchError = UpdateColumnApiColumnPatchErrors[keyof UpdateColumnApiColumnPatchErrors];

export type UpdateColumnApiColumnPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetColumnApiColumnPostData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/column/';
};

export type GetColumnApiColumnPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetColumnApiColumnPostError = GetColumnApiColumnPostErrors[keyof GetColumnApiColumnPostErrors];

export type GetColumnApiColumnPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpsertColumnApiColumnPutData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/column/';
};

export type UpsertColumnApiColumnPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertColumnApiColumnPutError = UpsertColumnApiColumnPutErrors[keyof UpsertColumnApiColumnPutErrors];

export type UpsertColumnApiColumnPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateColumnApiColumnInsertPutData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/column/insert';
};

export type CreateColumnApiColumnInsertPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateColumnApiColumnInsertPutError = CreateColumnApiColumnInsertPutErrors[keyof CreateColumnApiColumnInsertPutErrors];

export type CreateColumnApiColumnInsertPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteDataApiDataDeleteData = {
    body: BodyDeleteDataApiDataDelete;
    path?: never;
    query?: never;
    url: '/api/data/';
};

export type DeleteDataApiDataDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDataApiDataDeleteError = DeleteDataApiDataDeleteErrors[keyof DeleteDataApiDataDeleteErrors];

export type DeleteDataApiDataDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDataApiDataDeleteResponse = DeleteDataApiDataDeleteResponses[keyof DeleteDataApiDataDeleteResponses];

export type UpdateDataApiDataPatchData = {
    body: BodyUpdateDataApiDataPatch;
    path?: never;
    query?: never;
    url: '/api/data/';
};

export type UpdateDataApiDataPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDataApiDataPatchError = UpdateDataApiDataPatchErrors[keyof UpdateDataApiDataPatchErrors];

export type UpdateDataApiDataPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDataApiDataPostData = {
    body: CatalogInput;
    path?: never;
    query?: never;
    url: '/api/data/';
};

export type GetDataApiDataPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDataApiDataPostError = GetDataApiDataPostErrors[keyof GetDataApiDataPostErrors];

export type GetDataApiDataPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpsertDataApiDataPutData = {
    body: BodyUpsertDataApiDataPut;
    path?: never;
    query?: never;
    url: '/api/data/';
};

export type UpsertDataApiDataPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertDataApiDataPutError = UpsertDataApiDataPutErrors[keyof UpsertDataApiDataPutErrors];

export type UpsertDataApiDataPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateDataApiDataInsertPutData = {
    body: BodyCreateDataApiDataInsertPut;
    path?: never;
    query?: never;
    url: '/api/data/insert';
};

export type CreateDataApiDataInsertPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDataApiDataInsertPutError = CreateDataApiDataInsertPutErrors[keyof CreateDataApiDataInsertPutErrors];

export type CreateDataApiDataInsertPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/session/';
};

export type GetSessionResponses = {
    /**
     * Successful Response
     */
    200: CatalogOutput;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type ListSystemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/session/systems';
};

export type ListSystemsResponses = {
    /**
     * Response List Systems
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ListSystemsResponse = ListSystemsResponses[keyof ListSystemsResponses];

export type ListRegistryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registry/';
};

export type ListRegistryResponses = {
    /**
     * Response List Registry
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ListRegistryResponse = ListRegistryResponses[keyof ListRegistryResponses];

export type DeleteRegistryEntryData = {
    body?: never;
    path: {
        /**
         * Registry Key
         */
        registry_key: string;
    };
    query?: never;
    url: '/api/registry/{registry_key}';
};

export type DeleteRegistryEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRegistryEntryError = DeleteRegistryEntryErrors[keyof DeleteRegistryEntryErrors];

export type DeleteRegistryEntryResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRegistryEntryResponse = DeleteRegistryEntryResponses[keyof DeleteRegistryEntryResponses];

export type GetRegistryEntryData = {
    body?: never;
    path: {
        /**
         * Registry Key
         */
        registry_key: string;
    };
    query?: never;
    url: '/api/registry/{registry_key}';
};

export type GetRegistryEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRegistryEntryError = GetRegistryEntryErrors[keyof GetRegistryEntryErrors];

export type GetRegistryEntryResponses = {
    /**
     * Successful Response
     */
    200: CatalogOutput;
};

export type GetRegistryEntryResponse = GetRegistryEntryResponses[keyof GetRegistryEntryResponses];

export type SaveRegistryEntryData = {
    body: CatalogInput;
    path: {
        /**
         * Registry Key
         */
        registry_key: string;
    };
    query?: never;
    url: '/api/registry/{registry_key}';
};

export type SaveRegistryEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveRegistryEntryError = SaveRegistryEntryErrors[keyof SaveRegistryEntryErrors];

export type SaveRegistryEntryResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SaveRegistryEntryResponse = SaveRegistryEntryResponses[keyof SaveRegistryEntryResponses];

export type UploadFileData = {
    body: BodyUploadFile;
    path?: never;
    query?: never;
    url: '/api/files/upload';
};

export type UploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Response Upload File
     *
     * Successful Response
     */
    201: {
        [key: string]: unknown;
    };
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type ListMigrationPluginsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/migration/plugins';
};

export type ListMigrationPluginsResponses = {
    /**
     * Response List Migration Plugins
     *
     * Successful Response
     */
    200: Array<string>;
};

export type ListMigrationPluginsResponse = ListMigrationPluginsResponses[keyof ListMigrationPluginsResponses];

export type RunMigrationData = {
    body: MigrationRequest;
    path?: never;
    query?: never;
    url: '/api/migration/run';
};

export type RunMigrationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunMigrationError = RunMigrationErrors[keyof RunMigrationErrors];

export type RunMigrationResponses = {
    /**
     * Successful Response
     */
    200: MigrationResult;
};

export type RunMigrationResponse = RunMigrationResponses[keyof RunMigrationResponses];

export type SpaFallbackFullPathGetData = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/{full_path}';
};

export type SpaFallbackFullPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SpaFallbackFullPathGetError = SpaFallbackFullPathGetErrors[keyof SpaFallbackFullPathGetErrors];

export type SpaFallbackFullPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
