from __future__ import annotations

from typing import Any, Protocol, runtime_checkable, Literal
from .PluginModels import Catalog, Entity, Column, ArrowStream
from .PluginResponse import PluginResponse

@runtime_checkable
class Plugin(Protocol):
    """
    Universal interface for any data system.
    Five verbs:  create (DDL), get/read, update/alter, upsert, delete/drop
    Three nouns: catalog, entity, field
    stream:  
        Records - dictionary wrapped Iterable[dict[str, Any]]
        ArrowStream - PyArrow RecordBatchReader
    
    All operations return PluginResponse[T] - never raises for expected failures.
    PluginResponse.not_implemented() so the caller stays in control.
    Each Plugin handles its own batch limits internally.
    
    The catalogs and entities are the envelope that carries the metadata and context 
    needed to perform the requested operation.

    This is not an exhaustive list of what a plugin facade can provide, just the minimum core contract higher level services can rely on. And to ensure the developer is thinking about the core CRUD operations at every level of the system: Catalog, Entity, Field, and Records, as this program is more than a multi system orchestrator, its a universal data interaction and operator, and these are the core verbs and nouns of that language.

    By ensuring every plugin implements this core contract, services can be designed independent of the plugin. 

    kwargs can be used to pass along additional information your plugin may need. Perhaps you want to pass along a sql string for execution, or a dictionary of binds, or something specialized and specific to your plugin. That's fine, and that's what kwargs are for. This way you don't break other higher level services that rely on the core contract, but you can still provide additional functionality and flexibility for your plugin's unique features and capabilities.
    """
    # catalog aka: schema, namespace, database, folder, directory, etc. - the container of entities/objects/tables/files sharing the same namespace
    def create_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Catalog]: ...
    def get_catalog(self, catalog: Catalog, **kwargs: Any)    -> PluginResponse[Catalog]: ...
    def update_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Catalog]: ...
    def upsert_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Catalog]: ...
    def delete_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[None]: ...

    # entity aka: object, table, file/ etc. - the container of fields/columns
    def create_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Entity]: ...
    def get_entity(self, catalog: Catalog, **kwargs: Any)    -> PluginResponse[Entity]: ...
    def update_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Entity]: ...
    def upsert_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Entity]: ...
    def delete_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[None]: ...

    # field aka: column, attribute, properties etc. - the individual data points within an entity/table/file that act as locators for the actual data values, and have metadata describing the data type, format, constraints, etc.
    def create_field(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Column]: ...
    def get_field(self, catalog: Catalog, **kwargs: Any)    -> PluginResponse[Column]: ...
    def update_field(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Column]: ...
    def upsert_field(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Column]: ...
    def delete_field(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[None]: ...

    # data protocols - and how data might be requested and passed
    def get_data(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[ArrowStream]: ...
    def insert_data(self, catalog: Catalog, data: ArrowStream, **kwargs: Any) -> PluginResponse[ArrowStream]: ...
    def update_data(self, catalog: Catalog, data: ArrowStream, **kwargs: Any) -> PluginResponse[ArrowStream]: ...
    def upsert_data(self, catalog: Catalog, data: ArrowStream, **kwargs: Any) -> PluginResponse[ArrowStream]: ...
    def delete_data(self, catalog: Catalog, data: ArrowStream, **kwargs: Any) -> PluginResponse[None]: ...
    
    # Plugin Specifics
    def raw_query(self, **kwargs: Any) -> PluginResponse[ArrowStream]: ...
    def raw_command(self, **kwargs: Any) -> PluginResponse[Any]: ...

