from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable
from .PluginResponse import PluginResponse

if TYPE_CHECKING:
    from .PluginModels import ArrowReader, Catalog, Column, Entity

@runtime_checkable
class Plugin(Protocol):

    # catalog aka: schema, namespace, database, folder, directory, etc. - the container of entities/objects/tables/files sharing the same namespace
    
    def get_catalog(self, catalog: Catalog, **kwargs: Any)    -> PluginResponse[Catalog]: ...
    def create_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Catalog]: ...
    def update_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Catalog]: ...
    def upsert_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Catalog]: ...
    def delete_catalog(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[None]: ...

    # entity aka: object, table, file/ etc. - the container of columns/fields
    def create_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Entity]: ...
    def get_entity(self, catalog: Catalog, **kwargs: Any)    -> PluginResponse[Entity]: ...
    def update_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Entity]: ...
    def upsert_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Entity]: ...
    def delete_entity(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[None]: ...

    # column aka: field, attribute, properties etc. - the individual data points within an entity/table/file that act as locators for the actual data values, and have metadata describing the data type, format, constraints, etc.
    def create_column(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Column]: ...
    def get_column(self, catalog: Catalog, **kwargs: Any)    -> PluginResponse[Column]: ...
    def update_column(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Column]: ...
    def upsert_column(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[Column]: ...
    def delete_column(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[None]: ...

    # data protocols - and how data might be requested and passed
    def get_data(self, catalog: Catalog, **kwargs: Any) -> PluginResponse[ArrowReader]: ...
    def create_data(self, catalog: Catalog, data: ArrowReader, **kwargs: Any
                    ) -> PluginResponse[ArrowReader]: ...
    def update_data(self, catalog: Catalog, data: ArrowReader, **kwargs: Any
                    ) -> PluginResponse[ArrowReader]: ...
    def upsert_data(self, catalog: Catalog, data: ArrowReader, **kwargs: Any
                    ) -> PluginResponse[ArrowReader]: ...
    def delete_data(self, catalog: Catalog, data: ArrowReader, **kwargs: Any
                    ) -> PluginResponse[None]: ...
    
    # Plugin Specifics
    # def raw_query(self, **kwargs: Any) -> PluginResponse[ArrowReader]: ...
    # def raw_command(self, **kwargs: Any) -> PluginResponse[Any]: ...

    """
    
    """