from __future__ import annotations
from typing import Any, Protocol, runtime_checkable
from server.models.ConnectorStandard import Schema, Table, Column, DataStream
from server.models.ConnectorResponse import ConnectorResponse


@runtime_checkable
class Connector(Protocol):
    """
    Universal interface for any data system.

    Five verbs:  create, get, update, upsert, delete
    Three nouns: schema, table, column
    One stream:  records (DataStream)

    All operations return ConnectorResponse[T] — never raises for expected
    failures. Use NotImplementedError only for hard crashes; prefer
    ConnectorResponse.not_implemented() so the caller stays in control.

    Each connector handles its own batch limits internally.
    """

    schema: Schema

    # Preflight check. Ensure the connector is live before processing occurs.
    # You may cache the underlying connection, but this must actively verify it.
    def test_connection(self) -> bool: ...

    # ── Schema ──
    def create_schema(self, schema: Schema | str, **kwargs: Any) -> ConnectorResponse[Schema]: ...
    def get_schema(self, schema: Schema | str | None = None, **kwargs: Any) -> ConnectorResponse[Schema]: ...
    def update_schema(self, schema: Schema | str, **kwargs: Any) -> ConnectorResponse[Schema]: ...
    def upsert_schema(self, schema: Schema | str, **kwargs: Any) -> ConnectorResponse[Schema]: ...
    def delete_schema(self, schema: Schema | str, **kwargs: Any) -> ConnectorResponse[Schema]: ...

    # ── Table ──
    def create_table(self, table: Table | str, **kwargs: Any) -> ConnectorResponse[Table]: ...
    def get_table(self, table: Table | str, **kwargs: Any) -> ConnectorResponse[Table]: ...
    def update_table(self, table: Table | str, **kwargs: Any) -> ConnectorResponse[Table]: ...
    def upsert_table(self, table: Table | str, **kwargs: Any) -> ConnectorResponse[Table]: ...
    def delete_table(self, table: Table | str, **kwargs: Any) -> ConnectorResponse[Table]: ...

    # ── Column ──
    def create_column(self, table: Table | str, column: Column | str, **kwargs: Any) -> ConnectorResponse[Column]: ...
    def get_column(self, table: Table | str, column: Column | str, **kwargs: Any) -> ConnectorResponse[Column]: ...
    def update_column(self, table: Table | str, column: Column | str, **kwargs: Any) -> ConnectorResponse[Column]: ...
    def upsert_column(self, table: Table | str, column: Column | str, **kwargs: Any) -> ConnectorResponse[Column]: ...
    def delete_column(self, table: Table | str, column: Column | str, **kwargs: Any) -> ConnectorResponse[Column]: ...

    # ── Records ──
    # DataStream = Iterable[dict[str, Any]]
    # Record operations wrap DataStream in ConnectorResponse so the service layer
    # gets a consistent shape: result.ok tells you if it worked, result.data is
    # the stream. Failed records, batch errors, and API responses all flow back
    # through result.data as dicts — build your response parser once, not per system.
    def create_records(self, table: Table | str, records: DataStream, **kwargs: Any) -> ConnectorResponse[DataStream]: ...
    def get_records(self, table: Table | str, **kwargs: Any) -> ConnectorResponse[DataStream]: ...
    def update_records(self, table: Table | str, records: DataStream, **kwargs: Any) -> ConnectorResponse[DataStream]: ...
    def upsert_records(self, table: Table | str, records: DataStream, **kwargs: Any) -> ConnectorResponse[DataStream]: ...
    def delete_records(self, table: Table | str, records: DataStream, **kwargs: Any) -> ConnectorResponse[DataStream]: ...
