drop table users;
create table users (
    id number generated always as identity,
    username varchar2(255) not null unique,
    email varchar2(255) not null unique,
    hashed_password varchar2(255) not null,
    is_active number default 1,
    primary key (id)
);

insert into users (username, email, hashed_password) values ('testuser', 'testuser@example.com', 'hashedpassword');
insert into users (username, email, hashed_password) values ('brudow', 'brudow@example.com', 'password');

insert into users (username, email, hashed_password) values ('admin', 'admin@example.com', '');

commit;

CREATE TABLE user_settings (
    -- Primary Key generated as Identity
    setting_id      NUMBER GENERATED BY DEFAULT AS IDENTITY 
                    CONSTRAINT pk_user_settings PRIMARY KEY,
    
    -- Foreign key to your main users table
    user_id         NUMBER NOT NULL,
    
    -- Setting details
    setting_key     VARCHAR2(100) NOT NULL,
    setting_value   VARCHAR2(4000),
    description     VARCHAR2(500),
    
    -- Audit Columns
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR2(100) NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by      VARCHAR2(100) NOT NULL,
    
    -- Constraints
    CONSTRAINT uq_user_setting_key UNIQUE (user_id, setting_key)
);