SELECT USERNAME 
FROM BRUDOW."USER"
WHERE USERNAME IN (SELECT USERNAME FROM BRUDOW."USER" GROUP BY USERNAME HAVING COUNT(USERNAME) > 1)
;


DECLARE 
    COUNTER NUMBER := 0;
    CURSOR USER_CURSOR IS SELECT USERNAME FROM BRUDOW."USER" GROUP BY USERNAME HAVING COUNT(USERNAME) > 1; 
    V_USERNAME BRUDOW."USER".USERNAME%TYPE;
BEGIN 
        FOR REC IN USER_CURSOR
        
    LOOP 
        COUNTER := COUNTER + 1;
        UPDATE BRUDOW."USER" 
        SET USERNAME = USERNAME || '_' || TO_CHAR(COUNTER)
        WHERE USERNAME = REC.USERNAME
        ; 
        COMMIT;
    END LOOP;
END;
/
