"""
DDL setup for application-managed tables.

Run this once (or on deploy) to create tables that do not exist yet.
Each statement is idempotent via existence checks so re-running is always safe.

Usage:
    python -m server.db.setup_tables
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import oracledb
from server.db.ServerDatabase import ServerDatabase

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# DDL statements
# ---------------------------------------------------------------------------

_CREATE_USER_SESSION = """
CREATE TABLE USER_SESSION (
    USER_SESSION_ID  NUMBER
                         GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT PK_USER_SESSION PRIMARY KEY,

    USERNAME         VARCHAR2(100 CHAR)               NOT NULL,
    TOKEN_HASH       VARCHAR2(64 CHAR)                NOT NULL,
    ISSUED_AT        TIMESTAMP WITH TIME ZONE         NOT NULL,
    EXPIRES_AT       TIMESTAMP WITH TIME ZONE         NOT NULL,
    IS_ACTIVE        NUMBER(1,0)  DEFAULT 1           NOT NULL,

    IP_ADDRESS       VARCHAR2(45 CHAR),
    USER_AGENT       VARCHAR2(512 CHAR),
    SESSION_DATA     CLOB,

    CREATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL,
    UPDATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL
)
"""

_CREATE_USER_SESSION_INDEXES = [
    "CREATE INDEX IDX_USER_SESSION_USERNAME  ON USER_SESSION (USERNAME)",
    "CREATE INDEX IDX_USER_SESSION_TOKEN     ON USER_SESSION (TOKEN_HASH)",
    "CREATE INDEX IDX_USER_SESSION_ACTIVE    ON USER_SESSION (IS_ACTIVE, EXPIRES_AT)",
]

_USER_SESSION_FK = """
ALTER TABLE USER_SESSION
ADD CONSTRAINT FK_USER_SESSION_USERNAME
FOREIGN KEY (USERNAME) REFERENCES "USER"(USERNAME)
RELY DISABLE NOVALIDATE
"""

# ---------------------------------------------------------------------------

_CREATE_USER_SIGN_IN = """
CREATE TABLE USER_SIGN_IN (
    USER_SIGN_IN_ID  NUMBER
                         GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT PK_USER_SIGN_IN PRIMARY KEY,

    USERNAME         VARCHAR2(100 CHAR)               NOT NULL,
    IP_ADDRESS       VARCHAR2(45 CHAR),
    USER_AGENT       VARCHAR2(512 CHAR),
    SUCCESS          NUMBER(1,0)  DEFAULT 0           NOT NULL,
    FAILURE_REASON   VARCHAR2(256 CHAR),

    CREATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL,
    UPDATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL
)
"""

_CREATE_USER_SIGN_IN_INDEXES = [
    "CREATE INDEX IDX_USER_SIGN_IN_USERNAME_DATE ON USER_SIGN_IN (USERNAME, CREATED_DATE)",
    "CREATE INDEX IDX_USER_SIGN_IN_IP_DATE        ON USER_SIGN_IN (IP_ADDRESS, CREATED_DATE)",
]

# ---------------------------------------------------------------------------

_CREATE_CATALOG_REGISTRY = """
CREATE TABLE CATALOG_REGISTRY (
    CATALOG_REGISTRY_ID  NUMBER
                             GENERATED BY DEFAULT AS IDENTITY
                             CONSTRAINT PK_CATALOG_REGISTRY PRIMARY KEY,

    OWNER        VARCHAR2(100 CHAR)  NOT NULL,
    REGISTRY_KEY VARCHAR2(256 CHAR)  NOT NULL,
    CATALOG_JSON CLOB               NOT NULL,

    CREATED_AT  TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP  NOT NULL,

    CONSTRAINT UQ_CATALOG_REGISTRY UNIQUE (OWNER, REGISTRY_KEY)
)
"""

_CREATE_CATALOG_REGISTRY_INDEXES = [
    "CREATE INDEX IDX_CATALOG_REGISTRY_OWNER ON CATALOG_REGISTRY (OWNER)",
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _table_exists(cur: oracledb.Cursor, table_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = :tn",
        {"tn": table_name.upper()},
    )
    return (cur.fetchone() or (0,))[0] > 0


def _column_exists(cur: oracledb.Cursor, table_name: str, column_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = :t AND COLUMN_NAME = :c",
        {"t": table_name.upper(), "c": column_name.upper()},
    )
    return (cur.fetchone() or (0,))[0] > 0


def _index_exists(cur: oracledb.Cursor, index_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_INDEXES WHERE INDEX_NAME = :idx",
        {"idx": index_name.upper()},
    )
    return (cur.fetchone() or (0,))[0] > 0


def _constraint_exists(cur: oracledb.Cursor, constraint_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = :cn",
        {"cn": constraint_name.upper()},
    )
    return (cur.fetchone() or (0,))[0] > 0


def _run(cur: oracledb.Cursor, sql: str, label: str) -> None:
    try:
        cur.execute(sql)
        logger.info(f"  OK  {label}")
    except oracledb.DatabaseError as exc:
        (error,) = exc.args
        logger.warning(f"  SKIP {label} - {error.message.strip()}")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def create_tables(server_db: ServerDatabase) -> None:
    """
    Idempotent setup:
      - Creates USER_SESSION and USER_SIGN_IN if missing.
      - Adds HASHED_PASSWORD column to the Salesforce-ingested USER table if missing.
    """

    con = server_db.connect()
    try:
        with con.cursor() as cur:
            # -- HASHED_PASSWORD on USER ------------------------------------
            if _table_exists(cur, "USER"):
                if not _column_exists(cur, "USER", "HASHED_PASSWORD"):
                    logger.info('Adding HASHED_PASSWORD to "USER"...')
                    _run(cur, 'ALTER TABLE "USER" ADD HASHED_PASSWORD VARCHAR2(255 CHAR)', 'ADD HASHED_PASSWORD')
                else:
                    logger.info('"USER".HASHED_PASSWORD already exists - skipping')
            else:
                logger.warning('"USER" table not found - skipping HASHED_PASSWORD column. Run migration first.')

            # -- USER_SESSION ------------------------------------------------
            if not _table_exists(cur, "USER_SESSION"):
                logger.info("Creating USER_SESSION...")
                _run(cur, _CREATE_USER_SESSION, "CREATE TABLE USER_SESSION")
            else:
                logger.info("USER_SESSION already exists - skipping")

            for ddl in _CREATE_USER_SESSION_INDEXES:
                idx_name = ddl.split("CREATE INDEX")[1].split(" ON ")[0].strip()
                if not _index_exists(cur, idx_name):
                    _run(cur, ddl, f"CREATE INDEX {idx_name}")

            if not _constraint_exists(cur, "FK_USER_SESSION_USERNAME"):
                _run(cur, _USER_SESSION_FK, "FK_USER_SESSION_USERNAME")

            # -- USER_SIGN_IN ------------------------------------------------
            if not _table_exists(cur, "USER_SIGN_IN"):
                logger.info("Creating USER_SIGN_IN...")
                _run(cur, _CREATE_USER_SIGN_IN, "CREATE TABLE USER_SIGN_IN")
            else:
                logger.info("USER_SIGN_IN already exists - skipping")

            for ddl in _CREATE_USER_SIGN_IN_INDEXES:
                idx_name = ddl.split("CREATE INDEX")[1].split(" ON ")[0].strip()
                if not _index_exists(cur, idx_name):
                    _run(cur, ddl, f"CREATE INDEX {idx_name}")

            # -- CATALOG_REGISTRY -------------------------------------------
            if not _table_exists(cur, "CATALOG_REGISTRY"):
                logger.info("Creating CATALOG_REGISTRY...")
                _run(cur, _CREATE_CATALOG_REGISTRY, "CREATE TABLE CATALOG_REGISTRY")
            else:
                logger.info("CATALOG_REGISTRY already exists - skipping")

            for ddl in _CREATE_CATALOG_REGISTRY_INDEXES:
                idx_name = ddl.split("CREATE INDEX")[1].split(" ON ")[0].strip()
                if not _index_exists(cur, idx_name):
                    _run(cur, ddl, f"CREATE INDEX {idx_name}")

        con.commit()
        logger.info("setup_tables: complete")

    except Exception:
        con.rollback()
        raise


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
    from server.db.db import server_db
    create_tables(server_db)
