"""
DDL setup for application-managed tables.

Run this once (or on deploy) to create tables that do not exist yet.
Each statement is idempotent via "CREATE TABLE ... IF NOT EXISTS" emulated
with an EXISTS check so re-running is always safe.

Usage:
    python -m server.db.setup_tables
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

# Allow running as __main__ from project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import oracledb
from server.core.OracleClient import OracleClient

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# DDL statements
# ---------------------------------------------------------------------------

_CREATE_USER_SESSION = """
CREATE TABLE USER_SESSION (
    USER_SESSION_ID  NUMBER
                         GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT PK_USER_SESSION PRIMARY KEY,

    -- Identity
    USERNAME         VARCHAR2(100 CHAR)               NOT NULL,

    -- Token (stored as SHA-256 hex digest — never the raw JWT)
    TOKEN_HASH       VARCHAR2(64 CHAR)                NOT NULL,
    ISSUED_AT        TIMESTAMP WITH TIME ZONE         NOT NULL,
    EXPIRES_AT       TIMESTAMP WITH TIME ZONE         NOT NULL,
    IS_ACTIVE        NUMBER(1,0)  DEFAULT 1           NOT NULL,

    -- Client metadata
    IP_ADDRESS       VARCHAR2(45 CHAR),
    USER_AGENT       VARCHAR2(512 CHAR),

    -- Per-session scratchpad: JSON blob for temp objects / state created during session
    SESSION_DATA     CLOB,

    -- Audit columns
    CREATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL,
    UPDATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL
)
"""

_CREATE_USER_SESSION_INDEXES = [
    "CREATE INDEX IDX_USER_SESSION_USERNAME  ON USER_SESSION (USERNAME)",
    "CREATE INDEX IDX_USER_SESSION_TOKEN     ON USER_SESSION (TOKEN_HASH)",
    "CREATE INDEX IDX_USER_SESSION_ACTIVE    ON USER_SESSION (IS_ACTIVE, EXPIRES_AT)",
]

# Soft FK — references the app user table (RELY DISABLE NOVALIDATE so no hard enforcement)
# Adjust the parent table / column name if your user table differs.
_USER_SESSION_FK = """
ALTER TABLE USER_SESSION
ADD CONSTRAINT FK_USER_SESSION_USERNAME
FOREIGN KEY (USERNAME) REFERENCES "USER"(USERNAME)
RELY DISABLE NOVALIDATE
"""

# ---------------------------------------------------------------------------

_CREATE_USER_SIGN_IN = """
CREATE TABLE USER_SIGN_IN (
    USER_SIGN_IN_ID  NUMBER
                         GENERATED BY DEFAULT AS IDENTITY
                         CONSTRAINT PK_USER_SIGN_IN PRIMARY KEY,

    -- Who tried to sign in
    USERNAME         VARCHAR2(100 CHAR)               NOT NULL,

    -- Client metadata (used for rate-limit window queries)
    IP_ADDRESS       VARCHAR2(45 CHAR),
    USER_AGENT       VARCHAR2(512 CHAR),

    -- Outcome
    SUCCESS          NUMBER(1,0)  DEFAULT 0           NOT NULL,
    FAILURE_REASON   VARCHAR2(256 CHAR),

    -- Audit columns
    CREATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL,
    UPDATED_DATE     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(100 CHAR)       DEFAULT 'SYSTEM'           NOT NULL
)
"""

_CREATE_USER_SIGN_IN_INDEXES = [
    # Compound index supports the rate-limit query: username OR ip within a time window
    "CREATE INDEX IDX_USER_SIGN_IN_USERNAME_DATE ON USER_SIGN_IN (USERNAME, CREATED_DATE)",
    "CREATE INDEX IDX_USER_SIGN_IN_IP_DATE        ON USER_SIGN_IN (IP_ADDRESS, CREATED_DATE)",
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _table_exists(cur: oracledb.Cursor, table_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = :tn",
        tn=table_name.upper(),
    )
    row = cur.fetchone()
    return row is not None and row[0] > 0


def _index_exists(cur: oracledb.Cursor, index_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_INDEXES WHERE INDEX_NAME = :idx",
        idx=index_name.upper(),
    )
    row = cur.fetchone()
    return row is not None and row[0] > 0


def _constraint_exists(cur: oracledb.Cursor, constraint_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = :cn",
        cn=constraint_name.upper(),
    )
    row = cur.fetchone()
    return row is not None and row[0] > 0


def _run(cur: oracledb.Cursor, sql: str, label: str) -> None:
    try:
        cur.execute(sql)
        logger.info(f"  OK  {label}")
    except oracledb.DatabaseError as exc:
        (error,) = exc.args
        logger.warning(f"  SKIP {label} — {error.message.strip()}")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def create_tables(client: OracleClient | None = None) -> None:
    """
    Create USER_SESSION and USER_SIGN_IN tables (with indexes) if they do not
    already exist.  Pass an OracleClient to use an existing connection pool;
    omit to construct one from environment variables.
    """
    if client is None:
        client = OracleClient()

    con = client.connect()
    try:
        with con.cursor() as cur:
            # -- USER_SESSION ------------------------------------------------
            if not _table_exists(cur, "USER_SESSION"):
                logger.info("Creating USER_SESSION...")
                _run(cur, _CREATE_USER_SESSION, "CREATE TABLE USER_SESSION")
            else:
                logger.info("USER_SESSION already exists — skipping")

            for ddl in _CREATE_USER_SESSION_INDEXES:
                idx_name = ddl.split("CREATE INDEX")[1].split("ON")[0].strip()
                if not _index_exists(cur, idx_name):
                    _run(cur, ddl, f"CREATE INDEX {idx_name}")

            # -- USER_SIGN_IN ------------------------------------------------
            if not _table_exists(cur, "USER_SIGN_IN"):
                logger.info("Creating USER_SIGN_IN...")
                _run(cur, _CREATE_USER_SIGN_IN, "CREATE TABLE USER_SIGN_IN")
            else:
                logger.info("USER_SIGN_IN already exists — skipping")

            for ddl in _CREATE_USER_SIGN_IN_INDEXES:
                idx_name = ddl.split("CREATE INDEX")[1].split("ON")[0].strip()
                if not _index_exists(cur, idx_name):
                    _run(cur, ddl, f"CREATE INDEX {idx_name}")

        con.commit()
        logger.info("setup_tables: complete")

    except Exception:
        con.rollback()
        raise


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
    create_tables()
